name: Test workflow
on: [workflow_dispatch]
  inputs:
      GITHUB_ENVIRONMENT:
        required: true
        type: string
        description: "Environment"

env:
  Name: ${{ vars.name }}

jobs:
  echo-name:
    runs-on: ubuntu-latest
    
    steps:
      - name: Echo the users name
        run: |
          echo "${{vars.name}}"
      
  
