name: Test workflow (development)

on: 
  workflow_call:
    inputs:
      GITHUB_ENVIRONMENT:
        required: true
        type: string
        description: "Environment"
        
jobs:
  echo-name:
    environment: ${{inputs.GITHUB_ENVIRONMENT}}
    container: redhat/ubi8
    runs-on: ubuntu-latest
    steps:
      - name: Echo the users name
        run: |
          echo The environment is ${{ vars.ENV_NAME }},
          echo and the users name is ${{ vars.NAME }}.
      - name: Echo the name and release of the container
        run: |
          echo the release is $(cat /etc/*release)
      
  
