name: Test workflow
on: [workflow_dispatch]

jobs:
  echo-name:
    runs-on: ubuntu-latest
    environment: development    
    steps:
      - name: Echo the users name
        run: |
          echo ${{ vars.NAME }}
      
  
