name: Test workflow
environment: development
on:
  workflow_dispatch:
    environment:
      description: 'Environment to run tests against'
      type: environment
      required: true

jobs:
  echo-name:
    runs-on: ubuntu-latest
    steps:
      - name: Echo the users name
        run: |
          echo The environment is ${{ vars.ENV_NAME }},
          echo and the users name is ${{ vars.NAME }}.
          
      
  
